spring.application.name=product-api

server.port=8080


# MySQL Database
spring.datasource.url=jdbc:mysql://localhost:3306/productdb
spring.datasource.username=root
spring.datasource.password=Vetri@261

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# See formatted SQL in console
spring.jpa.properties.hibernate.format_sql=true

